-- 修正自增主键语法：移除 GENERATED BY DEFAULT AS IDENTITY，仅保留 AUTO_INCREMENT（H2 兼容）
-- 1. 创建系统用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- H2 支持的时间字段类型
    );

-- 2. 创建书架表
CREATE TABLE IF NOT EXISTS sys_shelf (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    shelf_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    create_user_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (create_user_id) REFERENCES sys_user (id) ON DELETE CASCADE
    );

-- 3. 创建书籍表
CREATE TABLE IF NOT EXISTS sys_book (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    book_name VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    cover_path VARCHAR(500),
    file_path VARCHAR(500) NOT NULL,
    format VARCHAR(10) NOT NULL,
    shelf_id BIGINT NOT NULL,
    upload_user_id BIGINT NOT NULL,
    upload_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shelf_id) REFERENCES sys_shelf (id) ON DELETE CASCADE,
    FOREIGN KEY (upload_user_id) REFERENCES sys_user (id) ON DELETE CASCADE
    );

-- 4. 创建书籍章节表
CREATE TABLE IF NOT EXISTS book_chapter (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    chapter_title VARCHAR(255) NOT NULL,
    chapter_content TEXT NOT NULL,
    chapter_order INT NOT NULL,
    book_id BIGINT NOT NULL,
    CONSTRAINT fk_book_chapter_book FOREIGN KEY (book_id) REFERENCES sys_book (id) ON DELETE CASCADE
    );

-- 5. 创建阅读记录表
CREATE TABLE IF NOT EXISTS read_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    read_position INT NOT NULL DEFAULT 0,
    last_read_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_read_record_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_read_record_book FOREIGN KEY (book_id) REFERENCES sys_book (id) ON DELETE CASCADE,
    CONSTRAINT fk_read_record_chapter FOREIGN KEY (chapter_id) REFERENCES book_chapter (id) ON DELETE CASCADE
    );

-- 转盘表（game_wheel）
CREATE TABLE game_wheel (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '转盘ID',
    name VARCHAR(64) NOT NULL COMMENT '转盘名称（如：酒桌惩罚转盘）',
    description VARCHAR(255) DEFAULT NULL COMMENT '转盘说明',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
);
-- 转盘选项表（game_wheel_item）
CREATE TABLE game_wheel_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '选项ID',
    wheel_id BIGINT NOT NULL COMMENT '所属转盘ID',
    content VARCHAR(128) NOT NULL COMMENT '选项内容（如：罚酒3杯）',
    type VARCHAR(32) DEFAULT '惩罚' COMMENT '类型：惩罚/奖励/互动/整蛊',
    weight INT NOT NULL DEFAULT 10 COMMENT '权重（越大概率越高）',
    color VARCHAR(32) DEFAULT '#FF5733' COMMENT '转盘颜色',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
);
-- 给转盘选项表创建索引
CREATE INDEX idx_wheel_id ON game_wheel_item(wheel_id);